Check that pcap_get_selectable_fd is declared in PCAP_IS_SUITABLE.
On AIX this test was passing even though this error happened on
compiling:
netutil.cc: In function 'int my_pcap_get_selectable_fd(pcap_t*)':
netutil.cc:870:34: error: 'pcap_get_selectable_fd' was not declared in this scope

git-svn-id: https://svn.nmap.org/nmap@26682 e0a8ed71-7df4-0310-8962-fdc924857419